services:
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: plazza
      MYSQL_USER: plazza
      MYSQL_PASSWORD: plazza
    volumes:
      - ./database:/var/lib/mysql
